twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/images': images

when@test:
    twig:
        strict_variables: true
