index:
    path: /
    controller: App\Controller\BookingController::homepage

addEmployee:
      path: /addEmployee
      controller: App\Controller\BookingController::addEmployee

addOffice:
      path: /addOffice
      controller: App\Controller\BookingController::addOffice

booking:
      path: /bookSeat/{day}/{officeId}
      defaults: {controller: App\Controller\BookingController::bookSeatOffice, day: null, officeId: null}
      requirements:
            day: .*
            officeId: .*

