#index:
#    path: /
#    controller: App\Controller\BookingController::index

addEmployee:
      path: /bookingController/addEmployee
      controller: App\Controller\BookingController::addEmployee

addOffice:
      path: /bookingController/addOffice
      controller: App\Controller\BookingController::addOffice
